[project]
name = "examples"
version = "0.1.0"
description = "Minimal example notebooks"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "metazoo",
    "numpy>=2.3.2",
    "jupyter>=1.1.1",
    "pandas>=2.3.3",
]

[tool.uv.sources]
metazoo = { path = "../metazoo", editable = true }
